name: Github Action Workflow DEV

on:
  push:
    branches:
      - dev
  repository_dispatch:
    types:
      - build-dev
  workflow_dispatch:

concurrency:
  group: environment-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-dev:
    uses: CAScompany/project-ShippingService/.github/workflows/shippingservice.yml@dev
    with:
      CI_ENV: dev
      CONTENTFUL_ENVIRONMENT: 'dev'
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN}}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      REGISTRY: ${{ secrets.REGISTRY }}
      ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
      TOKEN_RELEASE: ${{ secrets.TOKEN_RELEASE }}
      SLACK_WEBHOOK_URL: ${{secrets.SLACK_WEBHOOK_URL}}       